// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: CANopenMonitor

#ifndef _CANOPENMONITOR_UI_H
#define _CANOPENMONITOR_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

void Splash_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_Splash
void ui_Splash_screen_init(void);
void ui_event_Splash(lv_event_t * e);
extern lv_obj_t * ui_Splash;
extern lv_obj_t * ui_Splash_Label_splash;
// SCREEN: ui_Configure
void ui_Configure_screen_init(void);
extern lv_obj_t * ui_Configure;
extern lv_obj_t * ui_Configure_Container_Header;
extern lv_obj_t * ui_Configure_Label_Label2;
void ui_event_Configure_Button_Connect(lv_event_t * e);
extern lv_obj_t * ui_Configure_Button_Connect;
extern lv_obj_t * ui_Configure_Label_Label3;
extern lv_obj_t * ui_Configure_Label_Label4;
extern lv_obj_t * ui_Configure_Roller_Roller1;
extern lv_obj_t * ui_Configure_Label_Label5;
extern lv_obj_t * ui_Configure_Dropdown_Dropdown1;
extern lv_obj_t * ui_Startevents____initial_actions0;








void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
