// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: CANopenMonitor

#include "ui.h"
#include "esp_log.h"

void CANopenConnect(lv_event_t * e)
{
	// Your code here
	ESP_LOGI("ui_events", "Button Connect clicked.");
}
