// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: CANopenMonitor

#ifndef _UI_THEMES_H
#define _UI_THEMES_H

#ifdef __cplusplus
extern "C" {
#endif

#define UI_THEME_COLOR_COLORONE 0
#define UI_THEME_COLOR_COLORTWO 1
#define UI_THEME_COLOR_COLORTHREE 2
#define UI_THEME_COLOR_COLORFOUR 3
#define UI_THEME_COLOR_COLORFIVE 4

#define UI_THEME_DEFAULT 0

extern const ui_theme_variable_t _ui_theme_color_ColorOne[1];
extern const ui_theme_variable_t _ui_theme_alpha_ColorOne[1];

extern const ui_theme_variable_t _ui_theme_color_ColorTwo[1];
extern const ui_theme_variable_t _ui_theme_alpha_ColorTwo[1];

extern const ui_theme_variable_t _ui_theme_color_ColorThree[1];
extern const ui_theme_variable_t _ui_theme_alpha_ColorThree[1];

extern const ui_theme_variable_t _ui_theme_color_ColorFour[1];
extern const ui_theme_variable_t _ui_theme_alpha_ColorFour[1];

extern const ui_theme_variable_t _ui_theme_color_ColorFive[1];
extern const ui_theme_variable_t _ui_theme_alpha_ColorFive[1];

extern const uint32_t * ui_theme_colors[1];
extern const uint8_t * ui_theme_alphas[1];
extern uint8_t ui_theme_idx;

void ui_theme_set(uint8_t theme_idx);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
