// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: CANopenMonitor

#include "ui.h"


const ui_theme_variable_t _ui_theme_color_ColorOne[1] = {0xD32F2F};
const ui_theme_variable_t _ui_theme_alpha_ColorOne[1] = {255};

const ui_theme_variable_t _ui_theme_color_ColorTwo[1] = {0xF44336};
const ui_theme_variable_t _ui_theme_alpha_ColorTwo[1] = {255};

const ui_theme_variable_t _ui_theme_color_ColorThree[1] = {0x212121};
const ui_theme_variable_t _ui_theme_alpha_ColorThree[1] = {255};

const ui_theme_variable_t _ui_theme_color_ColorFour[1] = {0x9E9E9E};
const ui_theme_variable_t _ui_theme_alpha_ColorFour[1] = {255};

const ui_theme_variable_t _ui_theme_color_ColorFive[1] = {0x757575};
const ui_theme_variable_t _ui_theme_alpha_ColorFive[1] = {255};
uint8_t ui_theme_idx = UI_THEME_DEFAULT;


void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

