// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: CANopenMonitor

#include "../ui.h"

void ui_Splash_screen_init(void)
{
    ui_Splash = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Splash, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Splash, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_ColorThree);
    ui_object_set_themeable_style_property(ui_Splash, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_ColorThree);

    ui_Splash_Label_splash = lv_label_create(ui_Splash);
    lv_obj_set_width(ui_Splash_Label_splash, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Splash_Label_splash, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Splash_Label_splash, 0);
    lv_obj_set_y(ui_Splash_Label_splash, -30);
    lv_obj_set_align(ui_Splash_Label_splash, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Splash_Label_splash, "CANopenNode");
    ui_object_set_themeable_style_property(ui_Splash_Label_splash, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_ColorTwo);
    ui_object_set_themeable_style_property(ui_Splash_Label_splash, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_ColorTwo);
    lv_obj_set_style_text_font(ui_Splash_Label_splash, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Splash, ui_event_Splash, LV_EVENT_ALL, NULL);

}
